### ISSUE TITLE
TODO: Update the Travis CI Config for faster Test Times

### ISSUE THREAD

**Issue by raisedadead** [raisedadead/portfolio#94]
```yml
language: node_js

node_js:
  - 'lts/*'

cache:
  directories:
  - "$HOME/.npm"

env:
  global:
    - NO_UPDATE_NOTIFIER=1
    - NODE_NO_WARNINGS=1

sudo: false

before_install:
  - npm config set loglevel warn

install: npm ci

script:
  - npm run test
```
